version: "3.7"
networks:
  default:
    name: judgehost
    ipam:
      config:
        - subnet: "172.79.0.0/16"
          gateway: "172.79.0.1"
services:
  mariadb:
    image: mariadb:10.9
    command: ["--max-connections=1000"] 
    env_file: .env
    volumes:
      - $PWD/data/:/var/lib/mysql/

  domserver:
    image: domjudge/domserver:8.1.3
    env_file: .env
    ports: 
      - 12346:80
    depends_on:
      - mariadb

  judgehost:
    image: domjudge/judgehost:8.1.3
    hostname: judgedaemon-0
    depends_on:
      - domserver
    privileged: true
    volumes:
     - /sys/fs/cgroup/:/sys/fs/cgroup/:ro
    env_file: .env


